trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install --with-deps chromium
    displayName: 'Install Playwright Browsers'

  - script: npx playwright test
    displayName: 'Run Playwright tests'
    env:
      TEST_EMAIL: $(TEST_EMAIL)
      TEST_PASSWORD: $(TEST_PASSWORD)
      INVALID_LOGIN_EMAIL: $(INVALID_LOGIN_EMAIL)
      INVALID_LOGIN_PASSWORD: $(INVALID_LOGIN_PASSWORD)
      BASE_URL: $(BASE_URL)
      LOGIN_URL: $(LOGIN_URL)
      OUR_DESTINATIONS_URL: $(OUR_DESTINATIONS_URL)
      PAYMENT_CARD_NUMBER: $(PAYMENT_CARD_NUMBER)
      PAYMENT_EXPIRY: $(PAYMENT_EXPIRY)
      PAYMENT_CVC: $(PAYMENT_CVC)
      PAYMENT_NAME: $(PAYMENT_NAME)
      BILLING_COUNTRY: $(BILLING_COUNTRY)
      BILLING_STATE: $(BILLING_STATE)
      BILLING_CITY: $(BILLING_CITY)
      BILLING_ADDRESS_LINE1: $(BILLING_ADDRESS_LINE1)
      BILLING_ADDRESS_LINE2: $(BILLING_ADDRESS_LINE2)
      BILLING_ZIP_CODE: $(BILLING_ZIP_CODE)
      Exiting_Guest_User_Firt_Name: $(Exiting_Guest_User_Firt_Name)
      Exiting_Guest_User_Last_Name: $(Exiting_Guest_User_Last_Name)

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results/*.xml'
      failTaskOnFailedTests: false

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Allure Results'
    condition: always()
    inputs:
      targetPath: allure-results
      artifact: allure-results
